/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rzsupermarket.Interfaces;

import com.mycompany.rzsupermarket.Domain.Funcionario;
import com.mycompany.rzsupermarket.Services.FuncionarioDAO;
import com.mycompany.rzsupermarket.View.BancoDados;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Raf
 */
public class FuncionarioMenu extends javax.swing.JFrame {

    ListAllFuncionarios funcionariosAllList = new ListAllFuncionarios();
    List<Funcionario> listFuncionario = new ArrayList<>();
    FuncionarioDAO funcDAO = new FuncionarioDAO();
    DateTimeFormatter formater = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    BancoDados bd = new BancoDados();

    public FuncionarioMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSetor = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtSalario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AlterarSalario = new javax.swing.JButton();
        AlterarSetor = new javax.swing.JButton();
        txtDtNas = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Funcionarios ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Setor:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Sexo:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Data de Nascimento:");

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Lista de Funcionarios");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListFuncionarios(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Salario:");

        AlterarSalario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AlterarSalario.setText("Almentar Salario");
        AlterarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmentarSalario(evt);
            }
        });

        AlterarSetor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AlterarSetor.setText("Alterar Setor");
        AlterarSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarSetor(evt);
            }
        });

        try {
            txtDtNas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AlterarSetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlterarSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSalario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSetor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCPF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtNas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(276, 276, 276))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDtNas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(AlterarSalario)
                    .addComponent(AlterarSetor))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro
        if (!funcDAO.VerioficaPreenchimento(txtNome.getText(), txtCPF.getText(), txtSetor.getText(), txtDtNas.getText())) {
            JOptionPane.showMessageDialog(null, "Prencha os campos Vazios", "Mensagem do Sistema", JOptionPane.ERROR_MESSAGE);
        }

        String nome = txtNome.getText().trim();
        String data = txtCPF.getText().trim();
        char[] cpf = data.toCharArray();
        String setor = txtSetor.getText().trim();
        char sexo = txtSexo.getText().trim().charAt(0);
        String dataNas = txtDtNas.getText().trim();
        double salario = Double.parseDouble(txtSalario.getText().trim());

        LocalDate dtNasValidada = null;

        if (!funcDAO.validarData(dataNas)) {
            JOptionPane.showMessageDialog(null, "Data invalida", "Mensagem do Sistema", JOptionPane.ERROR_MESSAGE);
        } else {
            dtNasValidada = LocalDate.parse(dataNas, formater);
        }

        int idade = funcDAO.calcularIdade(dtNasValidada);

        Funcionario funcionarioAdicionar = new Funcionario(nome, cpf, setor, salario, sexo, idade, dtNasValidada);

        funcDAO.addFuncionario(listFuncionario, funcionarioAdicionar);


    }//GEN-LAST:event_Cadastro

    private void Buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar
        String cpf = JOptionPane.showInputDialog(null, "Informe o cpf do Funcionario", "Buscar Funcionario", JOptionPane.QUESTION_MESSAGE);

        funcDAO.buscarFunc(listFuncionario, cpf);
    }//GEN-LAST:event_Buscar

    private void Remover(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover
        String cpf = JOptionPane.showInputDialog(null, "Informe o cpf do Funcionario", "Remover Funcionario", JOptionPane.QUESTION_MESSAGE);

        funcDAO.removerFunc(listFuncionario, cpf);
    }//GEN-LAST:event_Remover

    private void ListFuncionarios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListFuncionarios
        funcionariosAllList.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        funcionariosAllList.setVisible(true);
        funcionariosAllList.carregarList(listFuncionario);
    }//GEN-LAST:event_ListFuncionarios

    private void AlmentarSalario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmentarSalario
        String cpf = JOptionPane.showInputDialog(null, "Informe o cpf do Funcionario", "Buscar Funcionario", JOptionPane.QUESTION_MESSAGE);
        String valor = JOptionPane.showInputDialog(null, "Informe o valor do almento", "Almento de Salario", JOptionPane.QUESTION_MESSAGE);
        double almento = Double.parseDouble(valor.trim());

        funcDAO.AlterarSalario(listFuncionario, cpf, almento);
    }//GEN-LAST:event_AlmentarSalario

    private void AlterarSetor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarSetor
        String cpf = JOptionPane.showInputDialog(null, "Informe o cpf do Funcionario", "Buscar Funcionario", JOptionPane.QUESTION_MESSAGE);
        String setor = JOptionPane.showInputDialog(null, "Informe o novo setor so Funcionario", "Almento de Salario", JOptionPane.QUESTION_MESSAGE);
        

        funcDAO.AlterarSetor(listFuncionario, cpf, setor);
    }//GEN-LAST:event_AlterarSetor

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FuncionarioMenu m = new FuncionarioMenu();
        try{
            m.bd.carregarListFuncionarios(m.listFuncionario);
        }catch(Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarSalario;
    private javax.swing.JButton AlterarSetor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtDtNas;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtSetor;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
